import {useEffect,useMemo,useState} from 'react';
import Editor from '@monaco-editor/react';
import {BookOpen, CheckCircle2, Code2, Play, Send, Search} from 'lucide-react';
import './index.css';

type Problem={id:string;number:number;title:string;chapter:string;difficulty:string;tags:string[];statement:string;explanation:string;hints:string[];starterCode:string;solutionCode:string;examples:{input:string;output:string}[]}
type Store={chapters:{id:string;title:string}[];problems:Problem[]}
const API=import.meta.env.VITE_API_URL||'http://localhost:8080';
function App(){const [store,setStore]=useState<Store>({chapters:[],problems:[]}); const [pid,setPid]=useState(''); const [query,setQuery]=useState(''); const [chapter,setChapter]=useState('all'); const [code,setCode]=useState(''); const [out,setOut]=useState(''); const [verdict,setVerdict]=useState(''); const [solved,setSolved]=useState<string[]>(()=>JSON.parse(localStorage.getItem('solved')||'[]'));
useEffect(()=>{fetch(API+'/api/problems').then(r=>r.json()).then(s=>{setStore(s); setPid(s.problems[0]?.id||''); setCode(s.problems[0]?.starterCode||'')})},[]);
const problem=store.problems.find(p=>p.id===pid); const filtered=useMemo(()=>store.problems.filter(p=>(chapter==='all'||p.chapter===chapter)&&((p.title+p.tags.join(' ')+p.statement).toLowerCase().includes(query.toLowerCase()))),[store,query,chapter]);
function select(p:Problem){setPid(p.id); setCode(localStorage.getItem('draft:'+p.id)||p.starterCode); setOut(''); setVerdict('')}
function saveDraft(v:string|undefined){const c=v||''; setCode(c); if(problem)localStorage.setItem('draft:'+problem.id,c)}
async function run(mode:string){setVerdict('Running...'); setOut(''); const r=await fetch(API+'/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({problemId:pid,code,mode})}); const j=await r.json(); setVerdict(j.verdict); setOut((j.error?j.error+'\n\n':'')+j.output+`\n\n${j.durationMs}ms`); if(mode==='submit'&&j.verdict==='Accepted'&&problem){const ns=[...new Set([...solved,problem.id])]; setSolved(ns); localStorage.setItem('solved',JSON.stringify(ns))}}
return <div className="min-h-screen"><header className="px-6 py-4 border-b border-zinc-800 flex items-center justify-between bg-black/30 sticky top-0 z-10 backdrop-blur"><div className="flex items-center gap-3"><div className="p-2 bg-white text-black rounded-xl"><Code2 size={20}/></div><div><h1 className="text-xl font-black">GoPrac</h1><p className="text-xs muted">LeetCode-style Go practice, locally run</p></div></div><div className="text-sm muted">{solved.length}/{store.problems.length} solved</div></header>
<div className="grid grid-cols-[340px_1fr] gap-4 p-4"><aside className="panel p-4 h-[calc(100vh-96px)] overflow-auto"><div className="flex items-center gap-2 mb-3 bg-zinc-950 border border-zinc-800 rounded-xl px-3"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search problems" className="bg-transparent outline-none py-3 w-full"/></div><select value={chapter} onChange={e=>setChapter(e.target.value)} className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-3 mb-4"><option value="all">All chapters</option>{store.chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><div className="space-y-2">{filtered.map(p=><button key={p.id} onClick={()=>select(p)} className={`w-full text-left p-3 rounded-xl border ${p.id===pid?'bg-zinc-100 text-black border-white':'bg-zinc-950 border-zinc-800 hover:border-zinc-600'}`}><div className="flex justify-between"><b>{p.number}. {p.title}</b>{solved.includes(p.id)&&<CheckCircle2 size={17} className="text-green-400"/>}</div><div className="text-xs opacity-70 mt-1">{p.difficulty} · {p.tags.slice(0,2).join(', ')}</div></button>)}</div></aside>
<main className="grid grid-cols-2 gap-4 h-[calc(100vh-96px)]">{problem&&<><section className="panel p-5 overflow-auto"><div className="flex items-center gap-2 muted text-sm"><BookOpen size={16}/>{store.chapters.find(c=>c.id===problem.chapter)?.title}</div><h2 className="text-3xl font-black mt-2">{problem.number}. {problem.title}</h2><div className="flex gap-2 my-4"><span className="chip">{problem.difficulty}</span>{problem.tags.map(t=><span className="chip" key={t}>{t}</span>)}</div><h3 className="font-bold text-lg">Problem</h3><p className="muted leading-7">{problem.statement}</p><h3 className="font-bold text-lg mt-5">Examples</h3>{problem.examples.map((e,i)=><pre key={i} className="bg-black border border-zinc-800 rounded-xl p-3 overflow-auto">Input: {e.input}\nOutput: {e.output}</pre>)}<h3 className="font-bold text-lg mt-5">Detailed explanation</h3><p className="muted leading-7">{problem.explanation}</p><h3 className="font-bold text-lg mt-5">Hints</h3><ol className="list-decimal ml-6 muted">{problem.hints.map(h=><li key={h}>{h}</li>)}</ol></section><section className="panel overflow-hidden flex flex-col"><div className="p-3 flex gap-2 justify-between border-b border-zinc-800"><div className="font-bold">Go editor</div><div className="flex gap-2"><button className="btn2" onClick={()=>run('run')}><Play size={15} className="inline"/> Run</button><button className="btn" onClick={()=>run('submit')}><Send size={15} className="inline"/> Submit</button></div></div><div className="flex-1"><Editor height="100%" defaultLanguage="go" theme="vs-dark" value={code} onChange={saveDraft} options={{fontSize:14,minimap:{enabled:false},scrollBeyondLastLine:false}}/></div><div className="h-48 border-t border-zinc-800 p-3 overflow-auto bg-black"><div className="font-bold mb-2">{verdict||'Output'}</div><pre className="text-sm whitespace-pre-wrap muted">{out||"Run code to see compile/runtime output. Submit runs this problem's local judge tests with a 3s timeout."}</pre></div></section></>}</main></div></div>}
export default App
